address: :8080
web: ./web/vue-frontend/dist/
dgtPort: /dev/ttyACM0
gamesFolder: ./games/
archiveFolder: ./games/archive/
engines:
  stockfish_14: /home/windler/projects/chess/chesspal/bin/stockfish_14
  komodo_12: /home/windler/projects/chess/chesspal/bin/komodo-12.1.1
bots:
  - name: Adrian (Komodo 1)
    engine: komodo_12
    depth: 9
    moveTimeMs: 300
    threads: 1
    options:
    - Skill=1
  - name: Bobby (Komodo 2)
    engine: komodo_12
    depth: 9
    moveTimeMs: 300
    threads: 1
    options:
    - Skill=2
  - name: Chrissy (Komodo 3)
    engine: komodo_12
    depth: 9
    moveTimeMs: 300
    threads: 1
    options:
    - Skill=3
  - name: Damian (Komodo 4)
    engine: komodo_12
    depth: 9
    moveTimeMs: 300
    threads: 1
    options:
    - Skill=4
  - name: Etienne (Komodo 5)
    engine: komodo_12
    depth: 9
    moveTimeMs: 300
    threads: 1
    options:
    - Skill=5
  - name: Freddy (Komodo 6)
    engine: komodo_12
    depth: 9
    moveTimeMs: 300
    threads: 1
    options:
    - Skill=6
  - name: Gerald (Komodo 7)
    engine: komodo_12
    depth: 9
    moveTimeMs: 300
    threads: 1
    options:
    - Skill=7
  - name: Herold (Komodo 8)
    engine: komodo_12
    depth: 9
    moveTimeMs: 300
    threads: 1
    options:
    - Skill=8
  - name: Lichess 1
    engine: stockfish_14
    depth: 5
    moveTimeMs: 50
    threads: 1
    options:
    - Skill Level=-9
  - name: Lichess 2
    engine: stockfish_14
    depth: 5
    moveTimeMs: 100
    threads: 1
    options:
    - Skill Level=-5
  - name: Lichess 3
    engine: stockfish_14
    depth: 5
    moveTimeMs: 150
    threads: 1
    options:
    - Skill Level=-1
eval:
  engine: stockfish_14
  depth: 20
  threads: 4
  moveTimeMs: 500
  options: []