address: :80
web: /home/pi/chesspal/web/vue-frontend/dist
dgtPort: /dev/ttyACM0
gamesFolder: /home/pi/games/
rclone:
  remote: chesspal
  games: true
engines:
  stockfish_12: /usr/games/stockfish
bots:
  - name: Lichess 1
    engine: stockfish_12
    depth: 5
    moveTimeMs: 50
    threads: 1
    options:
    - Skill Level=-9
  - name: Lichess 2
    engine: stockfish_12
    depth: 5
    moveTimeMs: 100
    threads: 1
    options:
    - Skill Level=-5
  - name: Lichess 3
    engine: stockfish_12
    depth: 5
    moveTimeMs: 150
    threads: 1
    options:
    - Skill Level=-1
eval:
  engine: stockfish_12
  depth: 20
  threads: 4
  moveTimeMs: 500
  options: []